name: Build and push Docker images

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      worker: ${{ steps.filter.outputs.worker }}
      api: ${{ steps.filter.outputs.api }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup filters
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            api:
              - 'api/**'
            frontend:
              - 'frontend/**'

  api:
    needs: setup
    if: needs.setup.outputs.api == 'true'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        working-directory: ./api/
        run: yarn

      - name: Build
        working-directory: ./api/
        run: yarn build

      - name: Test
        working-directory: ./api/
        run: yarn test --verbose --timeout 20000
        timeout-minutes: 2

      - name: Build Docker image
        run: docker build -t api ./api/

      - name: Tag Docker image with latest
        run: docker tag api hendrikutt/api:latest

      - name: Tag Docker image with commit hash
        run: docker tag api hendrikutt/api:${{ github.sha }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push hendrikutt/api:latest
          docker push hendrikutt/api:${{ github.sha }}

      - name: Install and setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup kubeconfig for api
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config

      - name: Set api Image to GitHub SHA
        run: kubectl set image deployment/api api=hendrikutt/api:${{ github.sha }}
      - name: Set api-reports-generator Image to GitHub SHA
        run: kubectl set image deployment/api-reports-generator api-reports-generator=hendrikutt/api:${{ github.sha }}

  frontend:
    needs: setup
    if: needs.setup.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./frontend/
        run: yarn

      - name: Test
        working-directory: ./frontend/
        run: yarn test --verbose
        timeout-minutes: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t frontend ./frontend/

      - name: Tag Docker image with latest
        run: docker tag frontend hendrikutt/frontend:latest

      - name: Tag Docker image with commit hash
        run: docker tag frontend hendrikutt/frontend:${{ github.sha }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push hendrikutt/frontend:latest
          docker push hendrikutt/frontend:${{ github.sha }}

      - name: Install and setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup kubeconfig for frontend
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config

      - name: Set Image to GitHub SHA
        run: kubectl set image deployment/frontend frontend=hendrikutt/frontend:${{ github.sha }}
